### ISSUE TITLE
Outdated and deprecated socket.io store.js use of __proto__

### ISSUE THREAD

**Issue by lielies** [wiseman/webflight-traffic#3]
I have been trying to get any these webflight projects working but can't seem to sort out the deprecated use of the __proto__ constructor they use for Inheritance within socket.io and express modules. Seems they have to be defined differently within the latest release of express. I keep getting the following ERROR when running cd ardrone-webflight && node app.js:

`C:\Users\8810255168084\affordable-fpv-drone-viewer\new-test\retest\ardrone-webfl
ight\node_modules\socket.io\lib\store.js:35
Store.prototype._ _proto_ _ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\Users\8810255168084\affordable-fpv-drone-viewer\ne
w-test\retest\ardrone-webflight\node_modules\socket.io\lib\store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\8810255168084\affordable-fpv-drone-viewer\ne
w-test\retest\ardrone-webflight\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:573:32)`

**Comment by wiseman** [comment]
It looks like this may be a general webflight issue that's not related specifically to webflight-traffic, is that right?  You might try opening an issue [there](https://github.com/eschnou/ardrone-webflight).
